[[plugins]]
package = "@netlify/plugin-lighthouse"

[build]
command = "pnpm build"
publish = "dist"

# Image optimization settings
[[redirects]]
from = "/img/*"
to = "/.netlify/images/:splat"
status = 200

[build.processing]
skip_processing = false

[build.processing.images]
compress = true
